# Generated by Django 4.2.1 on 2023-06-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeuroMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(verbose_name='Название метода')),
            ],
            options={
                'verbose_name': 'Метод',
                'verbose_name_plural': 'Методы',
            },
        ),
    ]
