# Generated by Django 4.2.1 on 2023-06-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_companies_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(verbose_name='Логин пользователя')),
                ('company_ticker', models.CharField(verbose_name='Тикер компании')),
                ('neuro_methods_list', models.TextField(verbose_name='Список методов для данной компании')),
                ('time_laps_list', models.CharField(verbose_name='Список временных промежутков')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
