# Generated by Django 4.2.1 on 2023-06-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_customsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsettings',
            name='company_name',
            field=models.CharField(default='company', verbose_name='Название компании'),
        ),
    ]
