# Generated by Django 4.2.1 on 2023-06-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_customsettings_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsettings',
            name='news_source_list',
            field=models.TextField(default='prnewswire.com,yahoo.com', verbose_name='Список новостных ресурсов для парсинга'),
        ),
    ]
