# Generated by Django 4.2.1 on 2023-06-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_customsettings_news_source_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsettings',
            name='neuro_methods_list',
            field=models.TextField(default='Нейросетевой анализ,Семантический анализ', verbose_name='Список методов для данной компании'),
        ),
    ]
