# Generated by Django 4.2.1 on 2023-06-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_customsettings_neuro_methods_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customsettings',
            unique_together={('user_name', 'company_ticker')},
        ),
    ]
