# Generated by Django 4.2.1 on 2023-05-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(verbose_name='Заголовок статьи')),
                ('annotation', models.TextField(default='', max_length=1000, verbose_name='Аннотация')),
                ('date', models.DateTimeField(verbose_name='Дата и время публикации')),
                ('source', models.CharField(verbose_name='Новостной источник')),
                ('company_name', models.CharField(verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
