# Generated by Django 4.2.1 on 2023-05-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(verbose_name='Новостной ресурс')),
            ],
            options={
                'verbose_name': 'Новостной ресурс',
                'verbose_name_plural': 'Новостные ресурсы',
            },
        ),
    ]
